services:
  web:
    container_name: podcast-app-web
    image: ${DOCKER_IMAGE:-podcast-app}
    build:
      context: .
      target: "service"
    ports:
      - 127.0.0.1:${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    profiles:
      - service
    environment:
      APP_SERVICE: web
      APP_VERSION: ${DOCKER_IMAGE_TAG:-latest}
      DB_HOST: db
      REDIS_HOST: redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", 'python -c "import os,socket; s=socket.socket(); s.connect((''127.0.0.1'', int(os.environ[''APP_PORT''])))"']
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 60s

  background:
    image: ${DOCKER_IMAGE_NAME:-podcast-service}:${DOCKER_IMAGE_TAG:-latest}
    container_name: podcast-app-background
    build:
      context: .
      target: "service"
    profiles:
      - service
    env_file:
      - .env
    environment:
      APP_SERVICE: background
      APP_VERSION: ${DOCKER_IMAGE_TAG:-latest}
      DB_HOST: db
      REDIS_HOST: redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      web:
        condition: service_healthy

  db:
    container_name: podcast-app-db
    image: postgres:17-alpine
    env_file:
      - .env
    profiles:
      - service
      - test
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - ${PWD}/.data/postgres:/var/lib/postgresql/data/pgdata

  redis:
    container_name: podcast-app-redis
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    profiles:
      - service
      - test
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - ${PWD}/.data/redis:/data

  test:
    container_name: podcast-app-test
    image: podcast-app:test
    profiles:
      - test
    env_file:
      - .env
    build:
      context: .
      target: tests
      args:
        DEV_DEPS: true
    environment:
      APP_SERVICE: test
      DB_HOST: db
      REDIS_HOST: redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  lint:
    container_name: podcast-app-lint
    image: podcast-app:test
    profiles:
      - test
    env_file:
      - .env
    build:
      context: .
      target: tests
      args:
        DEV_DEPS: true
    environment:
      APP_SERVICE: lint

networks:
  internal-subnet:
