"""
Initial migration (number supports for migration from podcast-service app)

Revision ID: 0022
Revises: 0021
Create Date: 2026-04-20 09:47:08.454984

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0022"
down_revision: Union[str, Sequence[str], None] = "0021"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=True),
        sa.Column("password", sa.String(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "auth_invites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=128), nullable=True),
        sa.Column("token", sa.String(length=32), nullable=False),
        sa.Column("is_applied", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("expired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["auth_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_auth_invites_token"), "auth_invites", ["token"], unique=True)
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("refresh_token", sa.String(length=512), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("expired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refreshed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_sessions_public_id"), "auth_sessions", ["public_id"], unique=True)
    op.create_table(
        "auth_user_access_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("token", sa.String(length=256), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("expires_in", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "auth_user_ips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hashed_address", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("registered_by", sa.String(length=128), server_default="", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_auth_user_ips__user_id__hashed_address",
        "auth_user_ips",
        ["user_id", "hashed_address"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auth_user_ips_registered_by"), "auth_user_ips", ["registered_by"], unique=False
    )
    op.create_table(
        "media_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Enum("AUDIO", "RSS", "IMAGE", name="media_type"), nullable=False),
        sa.Column("path", sa.String(length=256), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("source_url", sa.String(length=512), nullable=False),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.Column("access_token", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("public", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "meta", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True
        ),
        sa.Column("hash", sa.String(length=32), server_default="", nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["auth_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_media_files_access_token"), "media_files", ["access_token"], unique=True
    )
    op.create_index(op.f("ix_media_files_owner_id"), "media_files", ["owner_id"], unique=False)
    op.create_table(
        "podcast_cookies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("YOUTUBE", "YANDEX", "UPLOAD", name="source_type"),
            nullable=False,
        ),
        sa.Column("data", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["auth_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "podcast_podcasts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("publish_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("download_automatically", sa.Boolean(), nullable=False),
        sa.Column("rss_id", sa.Integer(), nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["image_id"], ["media_files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["auth_users.id"],
        ),
        sa.ForeignKeyConstraint(["rss_id"], ["media_files.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("publish_id"),
    )
    op.create_table(
        "podcast_episodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("source_id", sa.String(length=32), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("YOUTUBE", "YANDEX", "UPLOAD", name="source_type"),
            nullable=False,
        ),
        sa.Column("podcast_id", sa.Integer(), nullable=False),
        sa.Column("audio_id", sa.Integer(), nullable=True),
        sa.Column("image_id", sa.Integer(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("cookie_id", sa.Integer(), nullable=True),
        sa.Column("watch_url", sa.String(length=128), nullable=True),
        sa.Column("length", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "chapters", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True
        ),
        sa.Column("author", sa.String(length=256), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "DOWNLOADING",
                "CANCELING",
                "PUBLISHED",
                "ARCHIVED",
                "ERROR",
                "DL_PENDING",
                "DL_EPISODE_DOWNLOADING",
                "DL_EPISODE_POSTPROCESSING",
                "DL_EPISODE_UPLOADING",
                "DL_COVER_DOWNLOADING",
                "DL_COVER_UPLOADING",
                name="episode_status",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["audio_id"], ["media_files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["cookie_id"], ["podcast_cookies.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["image_id"], ["media_files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["auth_users.id"],
        ),
        sa.ForeignKeyConstraint(["podcast_id"], ["podcast_podcasts.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_podcast_episodes_owner_id"), "podcast_episodes", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_podcast_episodes_podcast_id"), "podcast_episodes", ["podcast_id"], unique=False
    )
    op.create_index(
        op.f("ix_podcast_episodes_source_id"), "podcast_episodes", ["source_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_podcast_episodes_source_id"), table_name="podcast_episodes")
    op.drop_index(op.f("ix_podcast_episodes_podcast_id"), table_name="podcast_episodes")
    op.drop_index(op.f("ix_podcast_episodes_owner_id"), table_name="podcast_episodes")
    op.drop_table("podcast_episodes")
    op.drop_table("podcast_podcasts")
    op.drop_table("podcast_cookies")
    op.drop_index(op.f("ix_media_files_owner_id"), table_name="media_files")
    op.drop_index(op.f("ix_media_files_access_token"), table_name="media_files")
    op.drop_table("media_files")
    op.drop_index(op.f("ix_auth_user_ips_registered_by"), table_name="auth_user_ips")
    op.drop_index("ix_auth_user_ips__user_id__hashed_address", table_name="auth_user_ips")
    op.drop_table("auth_user_ips")
    op.drop_table("auth_user_access_tokens")
    op.drop_index(op.f("ix_auth_sessions_public_id"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("ix_auth_invites_token"), table_name="auth_invites")
    op.drop_table("auth_invites")
    op.drop_table("auth_users")
    # ### end Alembic commands ###
