# Define backend application
upstream backend_app {
    server localhost:8000;
}

server {
    listen 80;
    server_name podcast.example.ru;

    # Hide nginx version
    server_tokens off;

    # Access logs
    access_log /var/log/nginx/podcast-example.log;
    error_log  /var/log/nginx/podcast-example-error.log;

    # Security headers
    add_header 'Strict-Transport-Security' "max-age=31536000"  always;
    add_header 'Content-Security-Policy' "style-src 'self' 'unsafe-inline'" always;
    add_header 'X-Frame-Options' "SAMEORIGIN" always;
    add_header 'X-Xss-Protection' "1; mode=block" always;
    add_header 'X-Content-Type-Options' "nosniff" always;
    add_header 'Referrer-Policy' 'strict-origin' always;
    add_header 'Feature-Policy' "autoplay 'none'; camera 'none'; document-domain 'none'; encrypted-media 'none'; fullscreen 'none'; geolocation 'none'; microphone 'none'; midi 'none'; payment 'none'; vr 'none'" always;

    # Common proxy settings
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Allow access to API docs and OpenAPI schema without authorization
    location /api/docs {
        proxy_pass http://backend_app;
    }

    location = /openapi.json {
        proxy_pass http://backend_app;
    }

    # Forward /api/* requests with auth check
    location /api/ {
        # Check Authorization header
        if ($http_authorization = "") {
            return 403;
        }

        proxy_pass http://backend_app;
    }

}
