import logging
from pathlib import Path
from typing import Mapping, Any

import yt_dlp

from src.settings.app import get_app_settings
from src.modules.common.types import YTDLParamsT
from src.modules.common.constants import EpisodeStatus
from src.modules.utils.common import logger
from src.modules.utils.processing import episode_process_hook


async def download_audio(
    source_url: str,
    filename: str,
    cookie_path: Path | None,
    proxy_url: str | None = None,
) -> Path:
    """
    Download providers video and perform to audio (.mp3) file

    :param source_url: URL to providers video which are needed to download
    :param filename: autogenerated filename for episode
    :param cookie_path: path to cookie's file for accessing to protected source
    :param proxy_url: proxy DSN for downloading video (specified for each source's type_
    :return path to downloaded file
    """
    settings = get_app_settings()
    result_path = settings.tmp_audio_path / filename
    params: YTDLParamsT = {
        "format": "bestaudio/best",
        "outtmpl": str(result_path),
        "logger": logging.getLogger("yt_dlp.YoutubeDL"),
        "progress_hooks": [download_process_hook],
        "noprogress": True,
        "cookiefile": str(cookie_path) if cookie_path else None,
    }

    if proxy_url:
        logger.info("YoutubeDL: Using proxy: %s", proxy_url)
        params["proxy"] = proxy_url

    with yt_dlp.YoutubeDL(params) as ydl:  # type: ignore
        ydl.download([source_url])

    return result_path


def download_process_hook(event: Mapping[str, Any]) -> None:
    """
    Allows handling processes of downloading episode's file.
    It is called by `yt_dlp.YoutubeDL`
    """
    total_bytes = _int_from_event(event, "total_bytes") or _int_from_event(
        event, "total_bytes_estimate"
    )
    downloaded_bytes = _int_from_event(event, "downloaded_bytes") or total_bytes
    filename = event.get("filename")
    if not isinstance(filename, str):
        logger.warning("Couldn't process download progress without filename: %s", event)
        return

    episode_process_hook(
        status=EpisodeStatus.DL_EPISODE_DOWNLOADING,
        filename=filename,
        total_bytes=total_bytes,
        processed_bytes=downloaded_bytes,
    )


def _int_from_event(event: Mapping[str, Any], key: str) -> int:
    value = event.get(key, 0)
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return int(value)
    if isinstance(value, str) and value.isdecimal():
        return int(value)
    return 0
